name: Update D-n Labels
on:
  schedule:
    - cron: '10 * * * *'
jobs:
  d-day-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Update D-n Labels
        uses: naver/d-day-labeler@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
